/*
Amber Electric Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	// Unique Site Identifier
	Id string `json:"id"`
	// National Metering Identifier (NMI) for the site
	Nmi string `json:"nmi"`
	// List of channels that are readable from your meter
	Channels []SitesChannels `json:"channels"`
	// The name of the site's network
	Network string `json:"network"`
}

// NewInlineResponse200 instantiates a new InlineResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200(id string, nmi string, channels []SitesChannels, network string) *InlineResponse200 {
	this := InlineResponse200{}
	this.Id = id
	this.Nmi = nmi
	this.Channels = channels
	this.Network = network
	return &this
}

// NewInlineResponse200WithDefaults instantiates a new InlineResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200WithDefaults() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// GetId returns the Id field value
func (o *InlineResponse200) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InlineResponse200) SetId(v string) {
	o.Id = v
}

// GetNmi returns the Nmi field value
func (o *InlineResponse200) GetNmi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nmi
}

// GetNmiOk returns a tuple with the Nmi field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetNmiOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Nmi, true
}

// SetNmi sets field value
func (o *InlineResponse200) SetNmi(v string) {
	o.Nmi = v
}

// GetChannels returns the Channels field value
func (o *InlineResponse200) GetChannels() []SitesChannels {
	if o == nil {
		var ret []SitesChannels
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetChannelsOk() ([]SitesChannels, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *InlineResponse200) SetChannels(v []SitesChannels) {
	o.Channels = v
}

// GetNetwork returns the Network field value
func (o *InlineResponse200) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetNetworkOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *InlineResponse200) SetNetwork(v string) {
	o.Network = v
}

func (o InlineResponse200) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["nmi"] = o.Nmi
	}
	if true {
		toSerialize["channels"] = o.Channels
	}
	if true {
		toSerialize["network"] = o.Network
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200 struct {
	value *InlineResponse200
	isSet bool
}

func (v NullableInlineResponse200) Get() *InlineResponse200 {
	return v.value
}

func (v *NullableInlineResponse200) Set(val *InlineResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200(val *InlineResponse200) *NullableInlineResponse200 {
	return &NullableInlineResponse200{value: val, isSet: true}
}

func (v NullableInlineResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


