/*
Amber Electric Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ActualIntervalAllOf1 struct for ActualIntervalAllOf1
type ActualIntervalAllOf1 struct {
	Type *string `json:"type,omitempty"`
}

// NewActualIntervalAllOf1 instantiates a new ActualIntervalAllOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActualIntervalAllOf1() *ActualIntervalAllOf1 {
	this := ActualIntervalAllOf1{}
	return &this
}

// NewActualIntervalAllOf1WithDefaults instantiates a new ActualIntervalAllOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActualIntervalAllOf1WithDefaults() *ActualIntervalAllOf1 {
	this := ActualIntervalAllOf1{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ActualIntervalAllOf1) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActualIntervalAllOf1) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ActualIntervalAllOf1) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ActualIntervalAllOf1) SetType(v string) {
	o.Type = &v
}

func (o ActualIntervalAllOf1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableActualIntervalAllOf1 struct {
	value *ActualIntervalAllOf1
	isSet bool
}

func (v NullableActualIntervalAllOf1) Get() *ActualIntervalAllOf1 {
	return v.value
}

func (v *NullableActualIntervalAllOf1) Set(val *ActualIntervalAllOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableActualIntervalAllOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableActualIntervalAllOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActualIntervalAllOf1(val *ActualIntervalAllOf1) *NullableActualIntervalAllOf1 {
	return &NullableActualIntervalAllOf1{value: val, isSet: true}
}

func (v NullableActualIntervalAllOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActualIntervalAllOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


