/*
Amber Electric Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ForecastIntervalAllOf Returns a forecasted price based on AEMO modelling. This is what AEMO thinks the price will be during the interval.
type ForecastIntervalAllOf struct {
	Type *string `json:"type,omitempty"`
	Range NullableForecastIntervalAllOfRange `json:"range,omitempty"`
}

// NewForecastIntervalAllOf instantiates a new ForecastIntervalAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastIntervalAllOf() *ForecastIntervalAllOf {
	this := ForecastIntervalAllOf{}
	return &this
}

// NewForecastIntervalAllOfWithDefaults instantiates a new ForecastIntervalAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastIntervalAllOfWithDefaults() *ForecastIntervalAllOf {
	this := ForecastIntervalAllOf{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ForecastIntervalAllOf) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastIntervalAllOf) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ForecastIntervalAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ForecastIntervalAllOf) SetType(v string) {
	o.Type = &v
}

// GetRange returns the Range field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ForecastIntervalAllOf) GetRange() ForecastIntervalAllOfRange {
	if o == nil || o.Range.Get() == nil {
		var ret ForecastIntervalAllOfRange
		return ret
	}
	return *o.Range.Get()
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ForecastIntervalAllOf) GetRangeOk() (*ForecastIntervalAllOfRange, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Range.Get(), o.Range.IsSet()
}

// HasRange returns a boolean if a field has been set.
func (o *ForecastIntervalAllOf) HasRange() bool {
	if o != nil && o.Range.IsSet() {
		return true
	}

	return false
}

// SetRange gets a reference to the given NullableForecastIntervalAllOfRange and assigns it to the Range field.
func (o *ForecastIntervalAllOf) SetRange(v ForecastIntervalAllOfRange) {
	o.Range.Set(&v)
}
// SetRangeNil sets the value for Range to be an explicit nil
func (o *ForecastIntervalAllOf) SetRangeNil() {
	o.Range.Set(nil)
}

// UnsetRange ensures that no value is present for Range, not even an explicit nil
func (o *ForecastIntervalAllOf) UnsetRange() {
	o.Range.Unset()
}

func (o ForecastIntervalAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Range.IsSet() {
		toSerialize["range"] = o.Range.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableForecastIntervalAllOf struct {
	value *ForecastIntervalAllOf
	isSet bool
}

func (v NullableForecastIntervalAllOf) Get() *ForecastIntervalAllOf {
	return v.value
}

func (v *NullableForecastIntervalAllOf) Set(val *ForecastIntervalAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastIntervalAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastIntervalAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastIntervalAllOf(val *ForecastIntervalAllOf) *NullableForecastIntervalAllOf {
	return &NullableForecastIntervalAllOf{value: val, isSet: true}
}

func (v NullableForecastIntervalAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastIntervalAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


